services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

  db-productores:
    image: postgres:16
    container_name: db-productores
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: productores
    ports:
      - "5433:5432"
    volumes:
      - productores_data:/var/lib/postgresql/data

  productores:
    build: ./productores
    container_name: productores
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: db-productores
    depends_on:
      - db-productores

  db-productos:
    image: postgres:16
    container_name: db-productos
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: productos
    ports:
      - "5434:5432"
    volumes:
      - productos_data:/var/lib/postgresql/data

  productos:
    build: ./productos
    container_name: productos
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: db-productos
      PRODUCTORES_URL: http://productores:8001
      USUARIOS_URL: http://usuarios:8006
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${DB_USER}
      MINIO_SECRET_KEY: ${DB_PASSWORD}
      MINIO_PUBLIC_URL: http://localhost:9000
      SERVICIO_SECRETO: clave-interna-servicios
    depends_on:
      - db-productos
      - productores

  db-pedidos:
    image: postgres:16
    container_name: db-pedidos
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: pedidos
    ports:
      - "5435:5432"
    volumes:
      - pedidos_data:/var/lib/postgresql/data

  pedidos:
    build: ./pedidos
    container_name: pedidos
    restart: unless-stopped
    ports:
      - "8003:8003"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: db-pedidos
      PRODUCTOS_URL: http://productos:8002
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin123
    depends_on:
    - db-pedidos
    - productos
    - rabbitmq

  db-transporte:
    image: postgres:16
    container_name: db-transporte
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: transporte
    ports:
      - "5436:5432"
    volumes:
      - transporte_data:/var/lib/postgresql/data

  transporte:
    build: ./transporte
    container_name: transporte
    restart: unless-stopped
    ports:
      - "8004:8004"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: db-transporte
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin123
      PEDIDOS_URL: http://pedidos:8003
    depends_on:
      - db-transporte
      - rabbitmq

  db-notificaciones:
    image: postgres:16
    container_name: db-notificaciones
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: notificaciones
    ports:
      - "5437:5432"
    volumes:
      - notificaciones_data:/var/lib/postgresql/data

  notificaciones:
    build: ./notificaciones
    container_name: notificaciones
    restart: unless-stopped
    ports:
      - "8005:8005"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: db-notificaciones
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin123
    depends_on:
      - db-notificaciones
      - rabbitmq

  db-usuarios:
    image: postgres:16
    container_name: db-usuarios
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: usuarios
    ports:
      - "5438:5432"
    volumes:
      - usuarios_data:/var/lib/postgresql/data

  usuarios:
    build: ./usuarios
    container_name: usuarios
    restart: unless-stopped
    ports:
      - "8006:8006"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db-usuarios
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db-usuarios

  db-pagos:
    image: postgres:16
    container_name: db-pagos
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: pagos
    ports:
      - "5439:5432"
    volumes:
      - pagos_data:/var/lib/postgresql/data

  pagos:
      build: ./pagos
      container_name: pagos
      restart: unless-stopped
      ports:
        - "8007:8007"
      environment:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: db-pagos
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_USER: admin
        RABBITMQ_PASSWORD: admin123
        JWT_SECRET: ${JWT_SECRET}
        CULQI_SECRET_KEY: ${CULQI_SECRET_KEY}
        SERVICIO_SECRETO: clave-interna-servicios
        PRODUCTOS_URL: http://productos:8002
      depends_on:
        - db-pagos
        - rabbitmq
  db-certificacion:
    image: postgres:16
    container_name: db-certificacion
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: certificacion
    ports:
      - "5440:5432"
    volumes:
      - certificacion_data:/var/lib/postgresql/data

  certificacion:
      build: ./certificacion
      container_name: certificacion
      restart: unless-stopped
      ports:
        - "8008:8008"
      environment:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: db-certificacion
        JWT_SECRET: ${JWT_SECRET}
        FRONTEND_URL: http://localhost:63342/mercado_agricola/frontend
      depends_on:
        - db-certificacion
volumes:
  productores_data:
  productos_data:
  pedidos_data:
  transporte_data:
  notificaciones_data:
  usuarios_data:
  pagos_data:
  certificacion_data: