apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificaciones
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notificaciones
  template:
    metadata:
      labels:
        app: notificaciones
    spec:
      containers:
        - name: notificaciones
          image: mercado_agricola-notificaciones:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8005
          env:
            - name: DB_HOST
              value: db-notificaciones
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_USER
              value: admin
            - name: RABBITMQ_PASSWORD
              value: admin123
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: credenciales-app
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credenciales-app
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: credenciales-app
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: notificaciones
spec:
  selector:
    app: notificaciones
  ports:
    - port: 8005
      targetPort: 8005