apiVersion: apps/v1
kind: Deployment
metadata:
  name: productos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: productos
  template:
    metadata:
      labels:
        app: productos
    spec:
      containers:
        - name: productos
          image: mercado_agricola-productos:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
            - name: DB_HOST
              value: db-productos
            - name: PRODUCTORES_URL
              value: http://productores:8001
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: credenciales-app
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credenciales-app
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: credenciales-app
                  key: JWT_SECRET
            - name: USUARIOS_URL
              value: http://usuarios:8006

            - name: MINIO_ENDPOINT
              value: minio:9000
            - name: MINIO_PUBLIC_URL
              value: http://localhost:9000
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: credenciales-app
                  key: DB_USER
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                   name: credenciales-app
                   key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: productos
spec:
  type: LoadBalancer
  selector:
    app: productos
  ports:
    - port: 8002
      targetPort: 8002