apiVersion: apps/v1
kind: Deployment
metadata:
  name: transporte
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transporte
  template:
    metadata:
      labels:
        app: transporte
    spec:
      containers:
        - name: transporte
          image: mercado_agricola-transporte:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          env:
            - name: DB_HOST
              value: db-transporte
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_USER
              value: admin
            - name: RABBITMQ_PASSWORD
              value: admin123
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: credenciales-app
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credenciales-app
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: credenciales-app
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: transporte
spec:
  type: LoadBalancer
  selector:
    app: transporte
  ports:
    - port: 8004
      targetPort: 8004