apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios
spec:
  replicas: 3
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
        - name: usuarios
          image: mercado_agricola-usuarios:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8006
          env:
            - name: DB_HOST
              value: db-usuarios
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: credenciales-app
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credenciales-app
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: credenciales-app
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: usuarios
spec:
  type: LoadBalancer
  selector:
    app: usuarios
  ports:
    - port: 8006
      targetPort: 8006